// 364 Ways to Say No - Complete Collection
// Each quote has a unique ID for analytics tracking
// Organized by rating (free, then 3-10)

export interface Quote {
  id: string;
  text: string;
  rating: 0 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
}

export const QUOTES_364: Record<string, Quote[]> = {
  free: [
    { id: "free-0", text: "\u201cI used extra-strength fabric softener and now my sheets are so slippery I\u2019ll slide off the bed like a wet seal.\u201d", rating: 0 },
    { id: "free-1", text: "I can\u2019t tonight. My cat\u2019s therapist says she needs more one\u2011to\u2011one time.", rating: 0 },
    { id: "free-2", text: "\u201cI would, but I\u2019ve already taken my bra off and that\u2019s the final stage of the evening.\u201d", rating: 0 }
  ],

  // Rating 3: Technical/Work frustration
  rating3: [
    { id: "3-0", text: "Excel just gaslit me for 45 minutes. I need recovery time.", rating: 3 },
    { id: "3-1", text: "I\u2019ve already performed emotional labour for capitalism today.", rating: 3 },
  ],

  // Rating 4: Funny/quirky one-liners and consequences
  rating4: [
    { id: "4-0", text: "I can't tonight \u2014 I can't go back to that library.", rating: 4 },
    { id: "4-1", text: "I would but,I got out of the car like a crime scene documentary extra.", rating: 4 },
    { id: "4-2", text: "The oven is preheating. We\u2019re married now.", rating: 4 },
    { id: "4-3", text: "I\u2019ve entered the \u201chave you tried turning it off and on again\u201d stage of grief.", rating: 4 },
    { id: "4-4", text: "The houseplants are giving me attitude. I need to negotiate.", rating: 4 },
    { id: "4-5", text: "Not tonight \u2014 I slept on my arm weird and it's made a noise that concerns me.", rating: 4 },
    { id: "4-6", text: "Not tonight \u2014 I've watched someone try to unmute for 8 minutes and it's drained my patience reserves.", rating: 4 },
    { id: "4-7", text: "My knees just sent me a formal complaint.", rating: 4 },
    { id: "4-8", text: "Not tonight \u2014 there's a light that comes on in a house I can see and it's on a schedule that's either routine or suspicious, and I must determine which.", rating: 4 },
    { id: "4-9", text: "Not tonight \u2014 my cousin's husband's mate did this once and the silence around it has never been broken.", rating: 4 },
    { id: "4-10", text: "Not tonight \u2014 something about the way a neighbour looks at their fence makes me think there's a story.", rating: 4 },
    { id: "4-11", text: "I can't \u2014 something's riding up and the solution requires removal and I'm staying home.", rating: 4 },
  ],

  // Rating 5: Comfort and self-care excuses
  rating5: [
    { id: "5-0", text: "I can't \u2014 Maureen did that and lost custody of something important.", rating: 5 },
    { id: "5-1", text: "Not tonight \u2014 someone will ask me questions and my vague answers aren't vague enough yet.", rating: 5 },
    { id: "5-2", text: "I would, but I\u2019ve promised myself an early night with a firm pillow and no surprises.", rating: 5 },
    { id: "5-3", text: "Sorry, but my phone storage is judging me.", rating: 5 },
    { id: "5-4", text: "Not tonight, The silence is finally returning my calls.", rating: 5 },
    { id: "5-5", text: "My soup is at the perfect temperature. I cannot abandon it.", rating: 5 },
    { id: "5-6", text: "Sorry, but I\u2019m emotionally buffering.", rating: 5 },
    { id: "5-7", text: "Not tonight \u2014 I'm in 3 group chats that are happening simultaneously and I'm choosing none of them.", rating: 5 },
    { id: "5-8", text: "I can\u2019t \u2014 Outlook has defeated me.", rating: 5 },
    { id: "5-9", text: "My introvert alarm just went off. Loudly.", rating: 5 },
    { id: "5-10", text: "I can't \u2014 something's gone numb in a way that's concerning and I need medical attention (or rest, I'm not sure).", rating: 5 },
    { id: "5-11", text: "I can't tonight \u2014 a friend once had a thing and now whenever I see a similar thing, I remember it.", rating: 5 },
    { id: "5-12", text: "Not tonight \u2014 I sneezed and something in my shoulder changed. I must investigate.", rating: 5 },
    { id: "5-13", text: "Not tonight \u2014 there's a person who did this and now they don't come to group things anymore.", rating: 5 },
    { id: "5-14", text: "Sorry, but something feels legally suspicious.", rating: 5 },
    { id: "5-15", text: "I can't \u2014 I wore new shoes for 20 minutes and now my feet are staging a formal protest.", rating: 5 },
    { id: "5-16", text: "I can't \u2014 my autocorrect just suggested something that made me question my entire phone.", rating: 5 },
    { id: "5-17", text: "I would, but I\u2019m trying to hear what the people on the next table are arguing about.", rating: 5 },
    { id: "5-18", text: "\u201cI\u2019d love to, but I\u2019m already fully stretched out in commitment.\u201d", rating: 5 },
    { id: "5-19", text: "I can't \u2014 someone's relative's pet has created a smell situation and I'm implicated just by living here.", rating: 5 },
    { id: "5-20", text: "I can\u2019t \u2014 the situation lacks stability.", rating: 5 },
    { id: "5-21", text: "I can't tonight. My friend's told me something outrageous about someone at the coffee morning and I need to process it in private.", rating: 5 },
    { id: "5-22", text: "Not tonight \u2014 Sharon from HR mentioned this came up once and she wasn't allowed to discuss the outcome.", rating: 5 },
    { id: "5-23", text: "Not tonight \u2014 I've tried to log in three times and now I'm locked out and I'm taking it as a sign.", rating: 5 },
    { id: "5-24", text: "Not now, dear \u2014 I\u2019ve reached the blanket stage of the day.", rating: 5 },
    { id: "5-25", text: "I can't \u2014 my partner's in a mood and I'm not risking making it worse by leaving.", rating: 5 },
    { id: "5-26", text: "Not tonight \u2014 a friend of mine got stuck in something embarrassing and now I'm paranoid about all similar situations.", rating: 5 },
    { id: "5-27", text: "I\u2019ve upset the energy of the room and now I must atone.", rating: 5 },
    { id: "5-28", text: "Not now, dear \u2014 I\u2019d prefer not to, thank you.", rating: 5 },
    { id: "5-29", text: "I stood up too quickly and my skeleton said no.", rating: 5 },
    { id: "5-30", text: "Not tonight \u2014 I've noticed something about the paint and now I've got opinions.", rating: 5 },
    { id: "5-31", text: "Not tonight \u2014 I've already forgiven one thing today and I'm maxed out.", rating: 5 },
    { id: "5-32", text: "I can't \u2014 I need a night where nothing fails to meet minimum expectations.", rating: 5 },
    { id: "5-33", text: "Not tonight \u2014 I've been asked not to return to that swimming pool.", rating: 5 },
    { id: "5-34", text: "Not tonight Sid \u2014 I slept slightly wrong and now I live like this.", rating: 5 },
    { id: "5-35", text: "I\u2019ve committed to staring at the wall with purpose.", rating: 5 },
    { id: "5-36", text: "I can't \u2014 I've decided someone owes me an apology and I'm rehearsing how to mention it.", rating: 5 },
    { id: "5-37", text: "Not tonight \u2014 I'm at the exact stage of the friendship where I still have to try and I'm exhausted by that.", rating: 5 },
    { id: "5-38", text: "Sorry \u2014 I\u2019ve started scrolling and I don\u2019t know where the bottom is.", rating: 5 },
    { id: "5-39", text: "The parrot said \u201cstay home\u201d and I respect his opinion.", rating: 5 },
    { id: "5-40", text: "\u201cAw babe, I\u2019m taken \u2014 by the couch. It\u2019s serious.\u201d", rating: 5 },
    { id: "5-41", text: "Not tonight \u2014 someone's posted something vague and cryptic and now I'm trying to decode what happened.", rating: 5 },
    { id: "5-42", text: "Not tonight \u2014 I've noticed the neighbours doing something odd and I've got research hours ahead.", rating: 5 },
    { id: "5-43", text: "I can't \u2014 I've got 6 unread notifications and I'm not emotionally prepared for even one of them.", rating: 5 },
    { id: "5-44", text: "Can't, I'm afraid. I've promised the budgie I'll read him the new Argos catalogue cover to cover.", rating: 5 },
    { id: "5-45", text: "Not tonight, love. I've got a suspicious twinge in my shoulder and I need to Google it until 2am.", rating: 5 },
    { id: "5-46", text: "I\u2019ve already smiled at someone this week. Quota met.", rating: 5 },
    { id: "5-47", text: "Not tonight \u2014 a neighbour has a routine that changed this week and now I'm wondering if they're okay or if something happened.", rating: 5 },
    { id: "5-48", text: "Not tonight \u2014 I\u2019ve got to rotate the mattress and emotionally prepare for it.", rating: 5 },
    { id: "5-49", text: "Not tonight \u2014 a neighbour casually mentioned their son's roommate situation and now I'm concerned and can't focus.", rating: 5 },
    { id: "5-50", text: "The moon is in a mood and I\u2019m not crossing her.", rating: 5 },
    { id: "5-51", text: "I can't \u2014 I've made a sandwich that's too ambitious to move with.", rating: 5 },
    { id: "5-52", text: "Not tonight, I\u2019ve just eaten a very large piece of cheddar and I\u2019m preparing for the vivid dreams.", rating: 5 },
    { id: "5-53", text: "I can't \u2014 I'm in a mood where I need substance, not just suggestions of it.", rating: 5 },
    { id: "5-54", text: "Sorry, but the hamster situation requires calm.", rating: 5 },
    { id: "5-55", text: "I can't tonight \u2014 I've already had enough disappointment this week and I'm protecting my reserves.", rating: 5 },
    { id: "5-56", text: "I can't \u2014 someone's turned their camera on unexpectedly and I've had an identity crisis.", rating: 5 },
    { id: "5-57", text: "Not tonight \u2014 there's a house that got a new fence and the colour choice is raising questions I didn't know I had.", rating: 5 },
    { id: "5-58", text: "Not tonight, darling. The neighbourhood WhatsApp group's having a crisis about someone's dustbin and I'm moderating.", rating: 5 },
    { id: "5-59", text: "Not tonight \u2014 I've had to smile professionally so much my face has filed a complaint.", rating: 5 },
    { id: "5-60", text: "I\u2019ve disappointed the sofa by standing up once already.", rating: 5 },
  ],

  // Rating 6: Mild inconveniences and quirky situations
  rating6: [
    { id: "6-0", text: "Not tonight \u2014 I\u2019ve finally got the heating exactly right and I don\u2019t want to disturb the balance.", rating: 6 },
    { id: "6-1", text: "Not tonight \u2014 my MIL texted something that suggests she's got opinions about tonight.", rating: 6 },
    { id: "6-2", text: "Terribly sorry \u2014 my diary says \u201cavoid people\u201d in very large font.", rating: 6 },
    { id: "6-3", text: "Not tonight \u2014 I\u2019m in the middle of a very tense game of \u2018Where\u2019s that smell coming from?\u2019", rating: 6 },
    { id: "6-4", text: "I can't \u2014 something's happened with my underwear situation and I'm managing it alone.", rating: 6 },
    { id: "6-5", text: "I can't \u2014 I've observed that someone always washes their car on Sundays but last Sunday they didn't and I've become concerned.", rating: 6 },
    { id: "6-6", text: "I cant luv The app crashed and took my entire personality with it.", rating: 6 },
    { id: "6-7", text: "I can't \u2014 I've decided I'm too old to pretend to care about this and I need to sit with that...", rating: 6 },
    { id: "6-8", text: "I sat in the wrong chair and now I\u2019m committed to this ache.", rating: 6 },
    { id: "6-9", text: "Not tonight \u2014 Rachel from admin said someone tried this and it became a policy update.", rating: 6 },
    { id: "6-10", text: "I can't \u2014 Karen did something similar and lost her job because of it.", rating: 6 },
    { id: "6-11", text: "Not tonight \u2014 I\u2019m trying to remember the name of that actor from that thing.", rating: 6 },
    { id: "6-12", text: "Not tonight \u2014 a neighbour has a routine that changed this week and now I'm wondering if they're okay or if something happened.", rating: 6 },
    { id: "6-13", text: "Not tonight \u2014 there's a house that got a new fence and the colour choice is raising questions I didn't know I had.", rating: 6 },
    { id: "6-14", text: "I can\u2019t \u2014 I\u2019ve spotted a pigeon on the fence and I need to monitor the situation.", rating: 6 },
    { id: "6-15", text: "I can't \u2014 my best friend's upset about something and I promised to help process it tonight.", rating: 6 },
    { id: "6-16", text: "I can't \u2014 there's a smell in the bathroom and the source investigation is ongoing.", rating: 6 },
    { id: "6-17", text: "Sorry \u2014 I\u2019ve started a documentary about castles and I\u2019m in too deep now.", rating: 6 },
    { id: "6-18", text: "Not tonight \u2014 I've remembered that one time I said something weird and everyone's probably still thinking about it.", rating: 6 },
    { id: "6-19", text: "Not tonight \u2014 I've noticed the neighbours doing something odd and I've got research hours ahead.", rating: 6 },
    { id: "6-20", text: "Not tonight \u2014 there's a person in our circle who did this and nobody brings it up anymore.", rating: 6 },
    { id: "6-21", text: "I can't \u2014 I've decided someone owes me an apology and I'm rehearsing how to mention it.", rating: 6 },
    { id: "6-22", text: "Sorry \u2014 I\u2019ve started scrolling and I don\u2019t know where the bottom is.", rating: 6 },
    { id: "6-23", text: "Not tonight \u2014 someone's posted something vague and cryptic and now I'm trying to decode what happened.", rating: 6 },
    { id: "6-24", text: "I\u2019ve already smiled at someone this week. Quota met.", rating: 6 },
    { id: "6-25", text: "Not tonight \u2014 I've noticed something about the paint and now I've got opinions.", rating: 6 },
    { id: "6-26", text: "I can't \u2014 I've got 6 unread notifications and I'm not emotionally prepared for even one of them.", rating: 6 },
  ],

  // Rating 7: Body issues and minor health concerns (104 quotes)
  rating7: [
    { id: "7-0", text: "Not tonight \u2014 my MIL's invited herself over and I need time to prepare emotionally.", rating: 7 },
    { id: "7-1", text: "Sunshine, you\u2019re missing the plot by about three episodes.", rating: 7 },
    { id: "7-2", text: "I can't tonight \u2014 I'm on chapter 47 of a book and the protagonist just made a terrible decision and I need to see if they survive it.", rating: 7 },
    { id: "7-3", text: "Not tonight \u2014 the cat's staring at nothing and I need to know if she's dying or just being dramatic.", rating: 7 },
    { id: "7-4", text: "Not a chance, darling. My perm's still setting and you know what they say about damp rollers and romance.", rating: 7 },
    { id: "7-5", text: "\u201cSorry love, my schedule\u2019s tight tonight\u2026 and so is my blanket.\u201d", rating: 7 },
    { id: "7-6", text: "I\u2019ve offended a seagull and now I\u2019m in hiding.", rating: 7 },
    { id: "7-7", text: "Can't tonight\u2014I've got to text my mate about what she said at bingo and it absolutely cannot wait.", rating: 7 },
    { id: "7-8", text: "Not tonight \u2014 I\u2019m waiting for my laundry to finish so I can ignore it.", rating: 7 },
    { id: "7-9", text: "I would, but I\u2019ve promised the dog I\u2019d help him stare at nothing in particular.", rating: 7 },
    { id: "7-10", text: "Not tonight \u2014 I\u2019m counting how many times the boiler clicks before bed.", rating: 7 },
    { id: "7-11", text: "I can't \u2014 I wore jeans with a real waistband and now I must lie down for 6 hours.", rating: 7 },
    { id: "7-12", text: "My cat just gave me a look that said \u201cyou\u2019re not going anywhere\u201d.", rating: 7 },
    { id: "7-13", text: "Not tonight \u2014 the rabbit has done something and I need to determine if it's a warning or a demand.", rating: 7 },
    { id: "7-14", text: "I can't \u2014 I've said something in a group chat and now I must monitor the response with paranoia.", rating: 7 },
    { id: "7-15", text: "Not tonight \u2014 my MIL's made a passive-aggressive comment and I'm still processing it.", rating: 7 },
    { id: "7-16", text: "Can't do it. My sister's neighbour's psychic says there's a tall dark stranger coming, but apparently it's the gas man.", rating: 7 },
    { id: "7-17", text: "I can\u2019t, darling. I\u2019ve just sat down and you know how long that took.", rating: 7 },
    { id: "7-18", text: "Kevin. My guy. You\u2019re really out here thinking I don\u2019t remember chapter one?", rating: 7 },
    { id: "7-19", text: "Not tonight Dave \u2014 I\u2019ve pulled something reaching for the remote.", rating: 7 },
    { id: "7-20", text: "Not tonight \u2014 my underwear situation requires immediate home intervention.", rating: 7 },
    { id: "7-21", text: "I can't \u2014 my mother-in-law's going to ask about something and I'm not prepared to answer.", rating: 7 },
    { id: "7-22", text: "I\u2019m in a passive-aggressive stand-off with my curlers.", rating: 7 },
    { id: "7-23", text: "How frightfully kind. Do pester me again when I'm accepting visitors. (I'm not.)", rating: 7 },
    { id: "7-24", text: "I can't \u2014 I've decided I'm not the kind of person who goes out on Thursdays and I need to commit to that brand.", rating: 7 },
    { id: "7-25", text: "I appreciate your optimism about my availability.", rating: 7 },
    { id: "7-26", text: "I can't \u2014 you mentioned something earlier and I'm still processing what you meant by it.", rating: 7 },
    { id: "7-27", text: "Not tonight \u2014 my gran did something similar and now she uses her mate's loyalty card so nobody knows it's her.", rating: 7 },
    { id: "7-28", text: "I can't \u2014 a mate told me something about a public toilet and now I've got that information forever.", rating: 7 },
    { id: "7-29", text: "Sorry, but I bent down and reconsidered my life.", rating: 7 },
    { id: "7-30", text: "Not tonight \u2014 a 9am meeting overran by 12 minutes and now everything's shifted and I can't readjust.", rating: 7 },
    { id: "7-31", text: "Not tonight \u2014 I\u2019ve got to re\u2011train my satnav after it called me \u2018mate\u2019.", rating: 7 },
    { id: "7-32", text: "I can\u2019t \u2014 I updated something and now nothing works.", rating: 7 },
    { id: "7-33", text: "I made a noise getting out of bed that legally counts as a cry for help.", rating: 7 },
    { id: "7-34", text: "Not tonight, darling. I'm in the middle of a very heated debate with myself about whether I unplugged the hair straighteners.", rating: 7 },
    { id: "7-35", text: "Not tonight \u2014 I'm in the middle of a mystery novel and I've just figured out who did it but I need to confirm I'm right.", rating: 7 },
    { id: "7-36", text: "Not tonight \u2014 I've opened the fancy biscuits and I must commit to finishing them tonight or they'll stale.", rating: 7 },
    { id: "7-37", text: "The fridge light judged me when I opened it. I can\u2019t leave now.", rating: 7 },
    { id: "7-38", text: "Not tonight \u2014 Pam tried this and she had a nervous breakdown that took years to recover from.", rating: 7 },
    { id: "7-39", text: "I'd rather not. The neighbours have just got a water bed and the walls are thinner than my patience.", rating: 7 },
    { id: "7-40", text: "Not tonight \u2014 my nan did that and now she orders everything online because she can't show her face.", rating: 7 },
    { id: "7-41", text: "Not tonight \u2014 Christine from HR's got a face she makes when certain things come up and I've learned to notice that face.", rating: 7 },
    { id: "7-42", text: "Not tonight \u2014 Debbie tried it and she got arthritis and nobody knows if they're connected but they might be.", rating: 7 },
    { id: "7-43", text: "Not tonight \u2014 I'm not in the mood to pretend.", rating: 7 },
    { id: "7-44", text: "I can\u2019t \u2014 I\u2019m keeping an eye on a cloud that looks like David Hasselhoff.", rating: 7 },
    { id: "7-45", text: "I can't \u2014 there's hair growing where it shouldn't and I haven't time to address it.", rating: 7 },
    { id: "7-46", text: "Not tonight \u2014 I stood up from sitting and made three separate noises. It's a bad sign.", rating: 7 },
    { id: "7-47", text: "Sorry petal \u2014 I\u2019ve got to finish knitting a scarf for a goose I met in Skegness.", rating: 7 },
    { id: "7-48", text: "Can't, darling. My support tights have developed a ladder and it's heading straight for my dignity.", rating: 7 },
    { id: "7-49", text: "Not tonight, dear. I\u2019ve just started a very intense relationship with a new brand of digestive biscuit.", rating: 7 },
    { id: "7-50", text: "My back just filed for divorce.", rating: 7 },
    { id: "7-51", text: "Not tonight \u2014 something's itching internally in a way I can't explain and I'm staying home.", rating: 7 },
    { id: "7-52", text: "Not tonight \u2014 I've just washed my hair and it\u2019s entered its \u2018don\u2019t touch me\u2019 phase.", rating: 7 },
    { id: "7-53", text: "Not tonight \u2014 I\u2019m defrosting a very large ham and it requires my undivided attention.", rating: 7 },
    { id: "7-54", text: "I can't \u2014 I'm scared I'll accidentally be funny and then I'll have to maintain that persona.", rating: 7 },
    { id: "7-55", text: "I can't \u2014 I saw a light in a supposedly empty building and now I've developed an obsession.", rating: 7 },
    { id: "7-56", text: "I can't \u2014 my hormones are having thoughts and I need to let them finish.", rating: 7 },
    { id: "7-57", text: "I can't \u2014 my mother-in-law's going to judge something and I'm not in the headspace for it.", rating: 7 },
    { id: "7-58", text: "Not tonight \u2014 something's leaked and I've got a stain situation that won't come out quickly.", rating: 7 },
    { id: "7-59", text: "I can't. I've just remembered something I said in 1987 and I need to sit with that for a while.", rating: 7 },
    { id: "7-60", text: "Not tonight \u2014 the charity shop on the corner and I have a situation.", rating: 7 },
    { id: "7-61", text: "I can't \u2014 I've made peace with one underwhelming situation and I'm not inviting another.", rating: 7 },
    { id: "7-62", text: "I can't \u2014 there's a night sweat situation and I've changed my clothes twice already.", rating: 7 },
    { id: "7-63", text: "Not now, dear \u2014 my back made a new sound today.", rating: 7 },
    { id: "7-64", text: "Not now, dear \u2014 I\u2019ve made tea and plans are cancelled.", rating: 7 },
    { id: "7-65", text: "I can't \u2014 Michelle did that and she ended up divorced over it.", rating: 7 },
    { id: "7-66", text: "I can\u2019t \u2014 I\u2019ve just remembered bin day and I don\u2019t trust myself.", rating: 7 },
    { id: "7-67", text: "Not tonight \u2014 a mate had a relative whose dog ate something it shouldn't and the vet bill story lives rent-free.", rating: 7 },
    { id: "7-68", text: "Not tonight \u2014 my gran got involved in something like this and had to write a letter of apology to Tesco.", rating: 7 },
    { id: "7-69", text: "I can't \u2014 my grandad mentioned doing this and his face suggested he's never recovered.", rating: 7 },
    { id: "7-70", text: "I can\u2019t \u2014 I sneezed and something shifted permanently.", rating: 7 },
    { id: "7-71", text: "Can\u2019t do it. My nightie\u2019s got a very low neckline tonight and it\u2019s making promises I can\u2019t keep.", rating: 7 },
    { id: "7-72", text: "Not tonight \u2014 my MIL's got that look on her face and I know what it means.", rating: 7 },
    { id: "7-73", text: "I can't \u2014 my bed sheets are at that stage and I'm considering my options.", rating: 7 },
    { id: "7-74", text: "Not tonight \u2014 a friend's said something to someone else and now there's a whole thing and I'm implicated.", rating: 7 },
    { id: "7-75", text: "I can't \u2014 I'm watching someone on a baking show make a critical error and I need to stay to see if the judges notice.", rating: 7 },
    { id: "7-76", text: "Darling, no \u2014 I\u2019ve got to finish writing a stern letter to the council about bin day.", rating: 7 },
    { id: "7-77", text: "I can't \u2014 I saw someone looking at their house from outside in a way that made me question what they were planning.", rating: 7 },
    { id: "7-78", text: "Not tonight Sid \u2014 I\u2019m supervising a slow-cooked evening.", rating: 7 },
    { id: "7-79", text: "\u201cI\u2019m afraid I\u2019ve got my hands full\u2026 with a very large mug of tea.\u201d", rating: 7 },
    { id: "7-80", text: "I would, but the dog next door barked earlier and I\u2019m still thinking about it.", rating: 7 },
    { id: "7-81", text: "Not tonight Dave \u2014 I\u2019ve been adopted temporarily by a dog.", rating: 7 },
    { id: "7-82", text: "I\u2019ve been cursed by a very small and vindictive ghost.", rating: 7 },
    { id: "7-83", text: "Not tonight \u2014 I had a friend who got chased by a goose and the trauma is secondhand but real.", rating: 7 },
    { id: "7-84", text: "Not tonight Brian \u2014 I\u2019m fully booked doing nothing.", rating: 7 },
    { id: "7-85", text: "Not tonight, love \u2014 I\u2019ve got to re\u2011train my satnav after it called me \u2018mate\u2019.", rating: 7 },
    { id: "7-86", text: "Dog sighed at me like I\u2019m the one who ruined his day.", rating: 7 },
    { id: "7-87", text: "I can\u2019t \u2014 I\u2019ve got a sock that\u2019s lost its partner and I need to support it.", rating: 7 },
    { id: "7-88", text: "I can't \u2014 I had a friend who had a situation involving a mirror and I'm not going into details but I can't look at mirrors the same way.", rating: 7 },
    { id: "7-89", text: "Can't tonight\u2014I've found a stain on the carpet I didn't know about yesterday and I need to decide if I'm upset or not.", rating: 7 },
    { id: "7-90", text: "Not tonight \u2014 elastic has failed in an embarrassing location and I'm not risking movement.", rating: 7 },
    { id: "7-91", text: "Not tonight \u2014 I've done the mental math and the conversation-to-effort ratio is unfavourable.", rating: 7 },
    { id: "7-92", text: "Can\u2019t \u2014 I\u2019ve got to finish this documentary about a man who collects spoons.", rating: 7 },
    { id: "7-93", text: "Not tonight Sid \u2014 the evening has gone sideways.", rating: 7 },
    { id: "7-94", text: "I can't \u2014 I need to sit with the last time something seemed promising then just... wasn't.", rating: 7 },
    { id: "7-95", text: "Not tonight \u2014 someone's described a medical emergency involving a frozen object and I need to process that.", rating: 7 },
    { id: "7-96", text: "I can't \u2014 I'm at that age where I've stopped being kind about things that simply aren't it.", rating: 7 },
    { id: "7-97", text: "Not tonight \u2014 Rachel attempted this and spent six months in hospital (for reasons she won't discuss).", rating: 7 },
    { id: "7-98", text: "I\u2019m in witness protection from small talk.", rating: 7 },
    { id: "7-99", text: "I've lost one of my favourite fuzzy socks. I can't possibly feel sexy when I have one cold foot and one warm foot. It's a sensory nightmare.", rating: 7 },
    { id: "7-100", text: "I can't \u2014 my grandad mentioned doing this and his face suggested he's never recovered.", rating: 7 },
    { id: "7-101", text: "Can\u2019t \u2014 I\u2019ve got to rewatch a show I don\u2019t even like out of sheer stubbornness.", rating: 7 },
    { id: "7-102", text: "Not tonight \u2014 I've noticed something about the paint and now I've got opinions.", rating: 7 },
    { id: "7-103", text: "I can't tonight \u2014 I've got a theory about what's happening in that one house and I need to sit with it.", rating: 7 },
  ],

  // Rating 8: More serious concerns, health issues, and consequences
  rating8: [
    { id: "8-0", text: "Not tonight \u2014 I've got wind issues and I'm not risking an enclosed space with people.", rating: 8 },
    { id: "8-1", text: "Not tonight \u2014 I'm banned from the Tesco on the high street and I'm not explaining why.", rating: 8 },
    { id: "8-2", text: "Not tonight \u2014 Margaret tried this once and she's been in therapy since.", rating: 8 },
    { id: "8-3", text: "I can't \u2014 I'm exhausted from the mental gymnastics required to make underwhelming work.", rating: 8 },
    { id: "8-4", text: "Not tonight \u2014 I was fine until someone mentioned 'staying up late' and now I'm exhausted on principle.", rating: 8 },
    { id: "8-5", text: "I can't \u2014 something I ate is having second thoughts and so am I.", rating: 8 },
    { id: "8-6", text: "I\u2019ve opened the posh crisps. Protocol has been activated.", rating: 8 },
    { id: "8-7", text: "Sorry \u2014 I\u2019ve just turned the big light off and there\u2019s no going back.", rating: 8 },
    { id: "8-8", text: "I can\u2019t, love. I\u2019ve gone into \"Power Save\" mode and my battery is currently at 2%.", rating: 8 },
    { id: "8-9", text: "Can't tonight\u2014I'm mentally preparing to ring the council about a pothole. They said to call back between 2 and 2:15pm next Thursday.", rating: 8 },
    { id: "8-10", text: "Babe\u2026 you\u2019re doing the thing again. We both know how this movie ends.", rating: 8 },
    { id: "8-11", text: "Cat sat on the keyboard and typed \u201cno\u201d seventeen times.", rating: 8 },
    { id: "8-12", text: "I can't \u2014 Wendy did that and she had to move to a different town.", rating: 8 },
    { id: "8-13", text: "Sorry, love \u2014 I\u2019ve just put a wash on and you know you can\u2019t start anything new once the spin cycle begins.", rating: 8 },
    { id: "8-14", text: "I can't \u2014 I knew someone whose pet did something irreversible and now certain animals make me nervous.", rating: 8 },
    { id: "8-15", text: "I would, but I\u2019ve promised myself I\u2019d finally Google that rash.", rating: 8 },
    { id: "8-16", text: "Not tonight, darling. The curtains need ironing and they're mocking me from the window.", rating: 8 },
    { id: "8-17", text: "Susan attempted this and her marriage never recovered.", rating: 8 },
    { id: "8-18", text: "I can't \u2014 my grandad mentioned his Tesco incident once and then refused to elaborate.", rating: 8 },
    { id: "8-19", text: "That's very kind, but I'm going to have to ask you not to ask again.", rating: 8 },
    { id: "8-20", text: "Sorry, but I\u2019m unavailable for enthusiasm this evening.", rating: 8 },
    { id: "8-21", text: "I\u2019ve committed an unforgivable amount of cheese tonight.", rating: 8 },
    { id: "8-22", text: "Not tonight\u2014I\u2019ve decided to see how long I can go without blinking while staring at this picture of a spaniel.", rating: 8 },
    { id: "8-23", text: "I can't \u2014 Kevin mentioned his mate did this and 'let's just say the company's lawyers were involved.", rating: 8 },
    { id: "8-24", text: "I can't tonight \u2014 I've got a situation with my pants that requires privacy.", rating: 8 },
    { id: "8-25", text: "My password manager is judging me.", rating: 8 },
    { id: "8-26", text: "Not tonight \u2014 someone I went to school with has posted something and the comments are a mess and I'm reading every single one.", rating: 8 },
    { id: "8-27", text: "I\u2019m busy trying to teach my Alexa how to speak with a Geordie accent and it\u2019s a full-time commitment.", rating: 8 },
    { id: "8-28", text: "Not tonight \u2014 my neighbour mentioned her daughter's boyfriend's van and now I'm worried about what's in it.", rating: 8 },
    { id: "8-29", text: "Not tonight \u2014 Janet at bingo mentioned this exact thing happening to her cousin and it took six months to resolve.", rating: 8 },
    { id: "8-30", text: "Not tonight \u2014 my mate's having a crisis about something and I'm the only one she'll talk to.", rating: 8 },
    { id: "8-31", text: "Not tonight \u2014 Linda tried this and she had to move house because of the fallout.", rating: 8 },
    { id: "8-32", text: "I can't \u2014 I've accidentally become invested in a minor neighbourhood dispute and I'm gathering evidence.", rating: 8 },
    { id: "8-33", text: "Not tonight \u2014 Janet mentioned someone did something similar and 'well, they don't live here anymore.", rating: 8 },
    { id: "8-34", text: "Not tonight \u2014 I'm at capacity for things that don't live up to their promise.", rating: 8 },
    { id: "8-35", text: "I can't tonight \u2014 my stomach's made a decision and I need to stay near the toilet.", rating: 8 },
    { id: "8-36", text: "Not tonight \u2014 my pants have given up and I've had to accept a new arrangement.", rating: 8 },
    { id: "8-37", text: "Not tonight \u2014 something's shifted in my closet and I need to assess the damage.", rating: 8 },
    { id: "8-38", text: "I can\u2019t \u2014 the dog is asleep on me and that\u2019s law.", rating: 8 },
    { id: "8-39", text: "I can't \u2014 there's a caf\u00e9 I can no longer visit and the staff know why.", rating: 8 },
    { id: "8-40", text: "Can\u2019t, pet. I\u2019ve promised the toaster I\u2019d spend more quality time with it.", rating: 8 },
    { id: "8-41", text: "I can't \u2014 I've seen something at number 47 that suggests a story I don't want to know.", rating: 8 },
    { id: "8-42", text: "I can't \u2014 Edna said she'd 'seen this before' in a tone that suggested nothing good came of it.", rating: 8 },
    { id: "8-43", text: "I can't \u2014 someone tried this and had to change their phone number because of the fallout.", rating: 8 },
    { id: "8-44", text: "I can\u2019t \u2014 I\u2019m trapped under something furry.", rating: 8 },
    { id: "8-45", text: "I can't tonight \u2014 Dave from accounts tried something like this and now he works from home permanently.", rating: 8 },
    { id: "8-46", text: "I can't \u2014 I've got a sweat patch situation that's beyond deodorant's capacity.", rating: 8 },
    { id: "8-47", text: "I can't \u2014 Edna mentioned a person who did this and then moved to Swindon very suddenly.", rating: 8 },
    { id: "8-48", text: "I can\u2019t. I\u2019m waiting for the washing machine to finish its dramatic finale.", rating: 8 },
    { id: "8-49", text: "I can't tonight \u2014 I've got a hot flash situation brewing and I'm staying near a fan.", rating: 8 },
    { id: "8-50", text: "Not tonight \u2014 I've heard a noise at 3am three times this month and I'm now documenting it.", rating: 8 },
    { id: "8-51", text: "I can\u2019t \u2014 I\u2019ve noticed a neighbour's curtains are never fully closed and I'm trying to respect their privacy while also being curious.", rating: 8 },
    { id: "8-52", text: "Not tonight \u2014 I\u2019ve just washed my hair and it\u2019s entered its \u2018don\u2019t touch me\u2019 phase.", rating: 8 },
    { id: "8-53", text: "I would, but the dog next door barked earlier and I\u2019m still thinking about it.", rating: 8 },
    { id: "8-54", text: "Not tonight \u2014 I\u2019ve committed to doing absolutely nothing and I must see it through.", rating: 8 },
    { id: "8-55", text: "I can't \u2014 my mother-in-law's been lovely lately and that's more suspicious than when she's difficult.", rating: 8 },
    { id: "8-56", text: "Tempting, but I\u2019ve slipped into something comfortable and I\u2019m not coming back.", rating: 8 },
    { id: "8-57", text: "Not tonight \u2014 Brenda attempted this and her family's still not speaking to her.", rating: 8 },
    { id: "8-58", text: "Sorry, duck. The sheets are freshly ironed and they\u2019re far too crisp to crumple yet.", rating: 8 },
    { id: "8-59", text: "Not tonight \u2014 I\u2019ve got crumbs in the bed and I need to investigate thoroughly.", rating: 8 },
    { id: "8-60", text: "I can\u2019t \u2014 the people two doors down have a situation brewing and I've accidentally got information I shouldn't have.", rating: 8 },
    { id: "8-61", text: "I can't \u2014 my mum's friend attempted this and her husband found out and that was the beginning of the end.", rating: 8 },
    { id: "8-62", text: "I can't \u2014 Janet said her sister-in-law's friend tried that and the samaritans got wind of it.", rating: 8 },
    { id: "8-63", text: "Not tonight \u2014 I\u2019m emotionally drained from arguing with the self\u2011checkout.", rating: 8 },
    { id: "8-64", text: "I would, but I've got a standing appointment with a very important pot of yoghurt that expires at midnight.", rating: 8 },
    { id: "8-65", text: "I\u2019d love to, but I\u2019ve just polished the floor and I\u2019m as slippery as a buttered eel on a lino surface.", rating: 8 },
    { id: "8-66", text: "\u201cNice try, but I\u2019m already fully committed\u2026 to my duvet.\u201d", rating: 8 },
    { id: "8-67", text: "The chocolate is already melting in my hand. It\u2019s too late.", rating: 8 },
    { id: "8-68", text: "Not tonight \u2014 I watched a neighbour's cat get stuck somewhere and now I have opinions about it.", rating: 8 },
    { id: "8-69", text: "Not tonight, pet \u2014 I\u2019ve promised the vicar I\u2019d keep my hands on something wholesome. The remote, mainly.", rating: 8 },
    { id: "8-70", text: "Not tonight \u2014 my bowels are in a mood and I need to be home for support.", rating: 8 },
    { id: "8-71", text: "I would, but I've just remembered I don't want to.", rating: 8 },
    { id: "8-72", text: "Not tonight\u2014I\u2019ve got a very demanding cat who insists on being the only thing I stroke after 9pm.", rating: 8 },
    { id: "8-73", text: "I can\u2019t, love. I\u2019ve just greased my muffin tins and if I start sliding around now, there\u2019ll be an incident.", rating: 8 },
    { id: "8-74", text: "I can\u2019t tonight. I\u2019m waiting for a parcel and the driver\u2019s \u2018two stops away\u2019 for the next six hours.", rating: 8 },
    { id: "8-75", text: "I can't tonight \u2014 my grandad did something like that once and he's banned from three places now.", rating: 8 },
    { id: "8-76", text: "I would, but I\u2019m saving my energy for something truly disappointing tomorrow.", rating: 8 },
    { id: "8-77", text: "I can't \u2014 my grandad warned me very specifically about attempting this.", rating: 8 },
    { id: "8-78", text: "Not tonight Brian \u2014 I\u2019ve opened snacks and that\u2019s binding.", rating: 8 },
    { id: "8-79", text: "Babe, you\u2019re missing the memo by several time zones.", rating: 8 },
    { id: "8-80", text: "I can't \u2014 I've started a true crime podcast and I'm three episodes in and now I'm convinced someone I know is suspicious.", rating: 8 },
    { id: "8-81", text: "Corporate has taken everything from me except this blanket.", rating: 8 },
    { id: "8-82", text: "I can't \u2014 I'm in a mood where I need substance, not just suggestions of it.", rating: 8 },
    { id: "8-83", text: "Not tonight, darling. The neighbourhood WhatsApp group's having a crisis about someone's dustbin and I'm moderating.", rating: 8 },
    { id: "8-84", text: "\u201cNot tonight \u2014 I\u2019m already getting very comfortable with someone who never disappoints me\u2026 my hot water bottle.\u201d", rating: 8 },
    { id: "8-85", text: "I\u2019d rather not put myself through that, thank you ever so much.", rating: 8 },
    { id: "8-86", text: "My back just filed for divorce.", rating: 8 },
    { id: "8-87", text: "Aw bless. Still haven\u2019t realised I keep the receipts, have you?", rating: 8 },
    { id: "8-88", text: "I can't \u2014 I know about another friend's embarrassing incident at a supermarket checkout and I can never unsee that place the same way.", rating: 8 },
    { id: "8-89", text: "I can\u2019t \u2014 the dog is asleep on me and that\u2019s law.", rating: 8 },
    { id: "8-90", text: "I can\u2019t \u2014 I\u2019ve upset a pigeon.", rating: 8 },
    { id: "8-91", text: "I can't \u2014 something's riding up and the solution requires removal and I'm staying home.", rating: 8 },
  ],

  // Rating 9: Serious incidents, major consequences, and significant stories
  rating9: [
    { id: "9-0", text: "Put it away Arthur; I\u2019ve already had my quota of excitement for this decade.", rating: 9 },
    { id: "9-1", text: "Not tonight \u2014 I\u2019ve got to re\u2011label all my spice jars after the cumin incident.", rating: 9 },
    { id: "9-2", text: "I can't tonight \u2014 Edna from bingo said she knew someone who did that and the council got involved.", rating: 9 },
    { id: "9-3", text: "Sorry, flower. The milkman left rather a lot this morning and I\u2019m still trying to get the cream off the top.", rating: 9 },
    { id: "9-4", text: "Not tonight \u2014 I've just found out my Spotify Wrapped was right about me and I'm depressed.", rating: 9 },
    { id: "9-5", text: "Sweetheart, point very much missed. Again.", rating: 9 },
    { id: "9-6", text: "Not tonight, darling. I've got to finish this crossword clue or it'll haunt me for the next fortnight.", rating: 9 },
    { id: "9-7", text: "I can't \u2014 I'm watching someone's Instagram story on mute to gather intelligence and I can't break my cover.", rating: 9 },
    { id: "9-8", text: "Kevin\u2026 point missed, map lost, GPS turned off. Iconic.", rating: 9 },
    { id: "9-9", text: "I can't tonight \u2014 I've noticed a neighbour has two identical cats and I'm trying to figure out if one is a decoy.", rating: 9 },
    { id: "9-10", text: "Kevin. We\u2019ve literally done this scene. I know your lines.", rating: 9 },
    { id: "9-11", text: "Not tonight Brian \u2014 that won\u2019t be necessary.", rating: 9 },
    { id: "9-12", text: "Not tonight \u2014 I\u2019m waiting for the cat to decide which room he wants to be in.", rating: 9 },
    { id: "9-13", text: "Not tonight, darling. I've got to finish this episode of casualty or I'll burst.", rating: 9 },
    { id: "9-14", text: "I would, but I've promised to help Margaret sort her pet budgie`s medication by day of the week and apparently I'm the only one she trusts.", rating: 9 },
    { id: "9-15", text: "Darling, no \u2014 I need a full orchestra, not a man turning up with a recorder.", rating: 9 },
    { id: "9-16", text: "I can't tonight \u2014 Tracy did something like that once and she's only got one leg now.", rating: 9 },
    { id: "9-17", text: "Not tonight \u2014 my hands have decided they're not gripping things today.", rating: 9 },
    { id: "9-18", text: "Sorry, but I\u2019ve opened the good chocolate.", rating: 9 },
    { id: "9-19", text: "Not a chance. My best bra\u2019s on strike and the girls refuse to come.", rating: 9 },
    { id: "9-20", text: "Sorry, pet. I've promised the cat I'll watch the Bridgerton with him. He gets very emotional when the queens on.", rating: 9 },
    { id: "9-21", text: "Not tonight \u2014 my nan tried that and she's still not allowed back at the Post Office.", rating: 9 },
    { id: "9-22", text: "Oh sweetheart, I would, but my lucky knickers are in quarantine.", rating: 9 },
    { id: "9-23", text: "Not a chance. The Avon lady's coming tomorrow and I need to look rested and slightly mysterious.", rating: 9 },
    { id: "9-24", text: "Not tonight \u2014 a work friend mentioned their sister's situation with a garden gnome and it's haunting me.", rating: 9 },
    { id: "9-25", text: "Not tonight \u2014 I'm too aware of what's actually happening to fake enthusiasm about what isn't.", rating: 9 },
    { id: "9-26", text: "Not tonight \u2014 I can't \u2014 someone's relative brought a parrot to a garden party and it said something weird and now I'm unsettled.", rating: 9 },
    { id: "9-27", text: "Not tonight \u2014 I've spotted someone's photo from 2009 and now I'm examining their entire Instagram history.", rating: 9 },
    { id: "9-28", text: "I\u2019d love to, but I\u2019ve just polished the floor and I\u2019m as slippery as a buttered eel on a lino surface.", rating: 9 },
    { id: "9-29", text: "Sorry love, but my horoscope said \u2018avoid unnecessary drama\u2019 and here we are.", rating: 9 },
    { id: "9-30", text: "Not a hope. My best slippers have gone walkabout and I won't be seen hobbling about like a wounded pigeon.", rating: 9 },
    { id: "9-31", text: "Not tonight \u2014 Edna casually mentioned it was illegal in 1987 and nobody checked if that's changed.", rating: 9 },
    { id: "9-32", text: "How lovely of you to think of me. Still no.", rating: 9 },
    { id: "9-33", text: "I can't \u2014 my mother-in-law's been quiet and that's worse than when she's loud.", rating: 9 },
    { id: "9-34", text: "I can't \u2014 I've decided I deserve a night where reality doesn't shrink on contact.", rating: 9 },
    { id: "9-35", text: "Aw, you\u2019re doing the hopeful-puppy-eyes sequel. I\u2019ve seen the reviews.", rating: 9 },
    { id: "9-36", text: "Not tonight \u2014 the dog's got me pinned to the sofa and honestly, I've accepted my fate.", rating: 9 },
    { id: "9-37", text: "Honey, I\u2019ve got a whole Netflix category named after your excuses.", rating: 9 },
    { id: "9-38", text: "I can't \u2014 my body's doing that thing where it leaks and I'm not confident I can manage it in public.", rating: 9 },
    { id: "9-39", text: "Not tonight \u2014 my knickers have migrated somewhere they shouldn't be and I need to fix this privately.", rating: 9 },
    { id: "9-40", text: "I can't \u2014 my face is doing something that requires concealer I haven't got time for.", rating: 9 },
    { id: "9-41", text: "Not tonight \u2014 I\u2019m in the middle of a very important sulk.", rating: 9 },
    { id: "9-42", text: "Dog is using me as an emotional support mattress.", rating: 9 },
    { id: "9-43", text: "Not tonight \u2014 I\u2019m halfway through judging the neighbours silently through the blinds.", rating: 9 },
    { id: "9-44", text: "Not tonight, pet \u2014 I\u2019ve promised Mrs Popadoplis I\u2019d help her glue googly eyes onto her garden gnomes.", rating: 9 },
    { id: "9-45", text: "I would, but Norma's cat has gone missing again and I've got to stand in the garden with a torch making clicking noises.", rating: 9 },
    { id: "9-46", text: "I'd love to, but my hot-water bottle has developed feelings and tonight's the night we have The Talk.", rating: 9 },
    { id: "9-47", text: "Not tonight \u2014 my underwear's decided today's the day it stops working as intended.", rating: 9 },
    { id: "9-48", text: "Not tonight, pet. I\u2019ve got to rehearse my disappointed sigh for tomorrow\u2019s effort.", rating: 9 },
    { id: "9-49", text: "Not now, dear \u2014 I\u2019d prefer not to, thank you.", rating: 9 },
    { id: "9-50", text: "Not tonight \u2014 my knickers have staged a rebellion and I'm not in a position to negotiate with them.", rating: 9 },
    { id: "9-51", text: "I can't \u2014 I'm in the middle of deciding whether to text someone I shouldn't and I need to stay focused on that.", rating: 9 },
  ],

  // Rating 10: Humorous one-liners and the most committed
  rating10: [
    { id: "10-0", text: "I\u2019ll have to give that a miss, if it\u2019s all the same to you.", rating: 10 },
    { id: "10-1", text: "I can't \u2014 I'm genuinely tired of the gap between what was implied and what showed up.", rating: 10 },
    { id: "10-2", text: "Not tonight \u2014 I\u2019ve got to re\u2011fold the towels because someone did it \u2018wrong\u2019 again.", rating: 10 },
    { id: "10-3", text: "Darling, you\u2019re giving main-character energy to a very side-character move.", rating: 10 },
    { id: "10-4", text: "Not tonight\u2014I'm in the middle of a very important disagreement with myself about whether I've locked the back door.", rating: 10 },
    { id: "10-5", text: "You\u2019re lovely, but I\u2019m afraid my boiler\u2019s acting up and I\u2019m waiting for a man with a much larger wrench.", rating: 10 },
    { id: "10-6", text: "Not tonight \u2014 Maureen said her late husband tried something similar and the insurance company are not paying out.", rating: 10 },
    { id: "10-7", text: "Not tonight\u2014I\u2019ve got a date with a bottle of Pinot and a very large bag of Monster Munch.", rating: 10 },
    { id: "10-8", text: "Not tonight \u2014 I'm not in the mood to pretend.", rating: 10 },
    { id: "10-9", text: "\u201cThanks for the invite, but I\u2019m already in bed with a good book.\u201d", rating: 10 },
  ]
};

// Get all quotes as flat array with IDs
export function getAllQuotes(): Quote[] {
  return [
    ...QUOTES_364.free as Quote[],
    ...(QUOTES_364.rating3 || []) as Quote[],
    ...(QUOTES_364.rating4 || []) as Quote[],
    ...(QUOTES_364.rating5 || []) as Quote[],
    ...(QUOTES_364.rating6 || []) as Quote[],
    ...(QUOTES_364.rating7 || []) as Quote[],
    ...(QUOTES_364.rating8 || []) as Quote[],
    ...(QUOTES_364.rating9 || []) as Quote[],
    ...(QUOTES_364.rating10 || []) as Quote[],
  ];
}

export const TOTAL_QUOTES = getAllQuotes().length;
